models/LoginForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

/**
 * LoginForm is the model behind the login form.
 */
class LoginForm extends Model
{

	public $apiKey;
	public $sessionId;

	/**
	 * @return array the validation rules.
	 */
	public function rules()
	{
		return [
			[
				'apiKey',
				'required',
			],
			[
				'apiKey',
				'getSessionId',
			],
		];
	}

	public function getSessionId($attribute, $params)
	{
		$tmdbService	 = new \app\helpers\TMDBService($this->{$attribute});
		$this->sessionId = $tmdbService->getSessionId();

		if (!$this->sessionId) {
			$this->addError($attribute, $tmdbService->getFirstError('apiKey'));
		}
	}

	public function login()
	{
		if ($this->validate()) {
			$user = new \app\models\User(['apiKey' => $this->apiKey]);

			if (Yii::$app->user->login($user, 3600)) {
				Yii::$app->session->set('sessionId', $this->sessionId);
				return true;
			}
		}
		return false;
	}

}

models/Movie.php
<?php

namespace app\models;

use \app\helpers\TMDBService;

class Movie extends \yii\db\ActiveRecord
{

	public function rules()
	{
		return [
			[
				[
					'id',
					'title',
					'original_title',
					'release_date',
					'runtime',
					'overview',
					'poster_path',
					'rating',
					'genres',
				],
				'safe',
			],
		];
	}

	protected static $requestUri = '/movie/';

	/**
	 * @var TMDBService
	 */
	protected $TMDBService;

	public static function findOne($condition, $TMDBService = null)
	{
		$model = parent::findOne($condition);
		if ($model === null && is_numeric($condition) && $TMDBService !== null) {
			$model = self::findOnTMDB($condition, $TMDBService);
		}

		$model->TMDBService = $TMDBService;

		return $model;
	}

	public static function findOnTMDB($id, TMDBService $TMDBService)
	{
		$movieData = $TMDBService->query(self::$requestUri . intval($id));

		if ($movieData['id']) {
			$genres = [];
			foreach ($movieData['genres'] as $genre) {
				$genres[] = $genre['name'];
			}
			$movieData['genres'] = implode(', ', $genres);

			$model = new static(array_intersect_key($movieData, self::getTableSchema()->columns));

			if ($model->poster_path) {
				$request	 = curl_init('https://image.tmdb.org/t/p/w185' . $model->poster_path);
				$savedImage	 = fopen(\Yii::getAlias('@webroot') . '/images' . $model->poster_path, 'wb');
				curl_setopt($request, CURLOPT_FILE, $savedImage);
				curl_setopt($request, CURLOPT_HEADER, 0);
				curl_exec($request);
				curl_close($request);
				fclose($savedImage);

				$model->poster_path = '/images' . $model->poster_path;
			}

			$model->save();

			return $model;
		}
	}

	public function beforeSave($insert)
	{
		if (!$insert && $this->oldAttributes['rating'] != $this->rating && $this->TMDBService !== null) {
			if (null === $this->TMDBService->query(self::$requestUri . intval($this->id) . '/rating', json_encode(['value' => floatval($this->rating)]))) {
				$this->addError('rating', $this->TMDBService->getFirstError('error'));
				return false;
			}
		}

		return parent::beforeSave($insert);
	}

	public function beforeDelete()
	{
		if ($this->poster_path && file_exists(\Yii::getAlias('@webroot') . $this->poster_path)) {
			unlink(\Yii::getAlias('@webroot') . $this->poster_path);
		}

		parent::beforeDelete();
	}

}

models/User.php
<?php

namespace app\models;

use Yii;

class User extends \yii\base\Object implements \yii\web\IdentityInterface
{

	public $apiKey;
	public $sessionId;

	/**
	 * @inheritdoc
	 */
	public static function findIdentity($id)
	{
		return new static(['apiKey' => $id, 'sessionId' => Yii::$app->session->get('sessionId')]);
	}

	/**
	 * @inheritdoc
	 */
	public static function findIdentityByAccessToken($token, $type = null)
	{
		return null;
	}

	/**
	 * @inheritdoc
	 */
	public function getId()
	{
		return $this->apiKey;
	}

	/**
	 * @inheritdoc
	 */
	public function getAuthKey()
	{
		return false;
	}

	/**
	 * @inheritdoc
	 */
	public function validateAuthKey($authKey)
	{
		return false;
	}

}

controllers/SiteController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;

class SiteController extends Controller
{

	public $defaultAction = 'movies';

	public function behaviors()
	{
		return [
			'access' => [
				'class'	 => AccessControl::className(),
				'only'	 => ['logout', 'movies'],
				'rules'	 => [
					[
						'actions'	 => ['logout', 'movies'],
						'allow'		 => true,
						'roles'		 => ['@'],
					],
				],
			],
			'verbs'	 => [
				'class'		 => VerbFilter::className(),
				'actions'	 => [
					'logout' => ['post'],
				],
			],
		];
	}

	public function actions()
	{
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionLogin()
	{
		if (!\Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new LoginForm();
		if ($model->load(Yii::$app->request->post()) && $model->login()) {
			return $this->redirect(['movies']);
		}

		return $this->render('login', [
				'model' => $model,
		]);
	}

	public function actionLogout()
	{
		Yii::$app->user->logout();

		return $this->goHome();
	}

	public function actionMovies($type = null)
	{
		$TMDBService		 = new \app\helpers\TMDBService(\Yii::$app->user->id, \Yii::$app->user->identity->sessionId);
		$TMDBMoviesProvider	 = new \app\helpers\TMDBMoviesProvider($TMDBService, $type);

		return $this->render('movies', [
				'moviesProvider' => $TMDBMoviesProvider,
		]);
	}

	public function actionMovie($id)
	{
		$TMDBService = new \app\helpers\TMDBService(\Yii::$app->user->id, \Yii::$app->user->identity->sessionId);

		if (($movie = \app\models\Movie::findOne($id, $TMDBService)) === null) {
			return $this->redirect(['movies']);
		}

		if (Yii::$app->getRequest()->isDelete) {
			$movie->delete();

			return $this->redirect(['movies']);
		} elseif (Yii::$app->getRequest()->isPost) {
			if ($movie->load(Yii::$app->getRequest()->post())) {
				$movie->save();
			}

			if (!$movie->hasErrors()) {
				return $this->refresh();
			}
		}

		return $this->render('movie', [
				'movie' => $movie,
		]);
	}

}

views/layouts/main.php
<?php
/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
	<head>
		<meta charset="<?= Yii::$app->charset ?>">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<?= Html::csrfMetaTags() ?>
		<title><?= Html::encode($this->title) ?></title>
		<?php $this->head() ?>
	</head>
	<body>
		<?php $this->beginBody() ?>

		<div class="wrap">
			<?php
			NavBar::begin([
				'brandLabel' => 'My Company',
				'brandUrl'	 => Yii::$app->homeUrl,
				'options'	 => [
					'class' => 'navbar-inverse navbar-fixed-top',
				],
			]);
			echo Nav::widget([
				'options'	 => ['class' => 'navbar-nav navbar-right'],
				'items'		 => [
					['label' => 'Movies', 'url' => ['/site/movies']],
					Yii::$app->user->isGuest ?
						['label' => 'Login', 'url' => ['/site/login']] :
						[
						'label'			 => 'Logout: ' . substr(Yii::$app->user->id, 0, 6) . "... (sessionId:" . substr(Yii::$app->user->identity->sessionId, 0, 6) . '...)',
						'url'			 => ['/site/logout'],
						'linkOptions'	 => ['data-method' => 'post']
						],
				],
			]);
			NavBar::end();
			?>

			<div class="container">
				<?=
				Breadcrumbs::widget([
					'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
				])
				?>
				<?= $content ?>
			</div>
		</div>

		<footer class="footer">
			<div class="container">
				<p class="pull-left">&copy; My Company <?= date('Y') ?></p>

				<p class="pull-right"><?= Yii::powered() ?></p>
			</div>
		</footer>

		<?php $this->endBody() ?>
	</body>
</html>
<?php $this->endPage() ?>

views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

views/site/login.php
<?php
/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title					 = 'Login';
$this->params['breadcrumbs'][]	 = $this->title;
?>
<div class="site-login">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to login:</p>

	<?php
	$form							 = ActiveForm::begin([
			'id'			 => 'login-form',
			'options'		 => ['class' => 'form-horizontal'],
			'fieldConfig'	 => [
				'template'		 => "{label}\n<div class=\"col-lg-3\">{input}</div>\n<div class=\"col-lg-8\">{error}</div>",
				'labelOptions'	 => ['class' => 'col-lg-1 control-label'],
			],
	]);
	?>

	<?= $form->field($model, 'apiKey') ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		</div>
	</div>

	<?php ActiveForm::end(); ?>
</div>

views/site/movie.php
<?php
/* @var $this yii\web\View */

use \yii\helpers\Html;
use \yii\widgets\ActiveForm;

$this->title					 = "Movie: {$movie->title} ({$movie->id})";
$this->params['breadcrumbs'][]	 = $this->title;
?>
<div class="site-movie">
    <h1>
		<?= Html::encode($this->title) ?>
		<?php
		echo Html::a('Delete', ['site/movie', 'id' => $movie->id], [
			'class'	 => 'btn btn-danger',
			'data'	 => [
				'confirm'	 => 'Are you sure you want to delete the movie?',
				'method'	 => 'DELETE',
			]
		]);
		?>
	</h1>

	<?php
	$form							 = ActiveForm::begin([
			'id'			 => 'login-form',
			'options'		 => ['class' => 'form-horizontal'],
			'fieldConfig'	 => [
				'template'		 => "{label}\n<div class=\"col-lg-6\">{input}</div>\n<div class=\"col-lg-4\">{error}</div>",
				'labelOptions'	 => ['class' => 'col-lg-2 control-label'],
			],
	]);
	?>

	<div class="form-group movie-poster">
		<label class="col-lg-2 control-label">Poster</label>
		<div class="col-lg-6">
			<?php
			if ($movie->poster_path) {
				echo '<img src="' . \Yii::getAlias('@web') . $movie->poster_path . '" />';
			}
			?>
		</div>
	</div>

	<?= $form->field($movie, 'title') ?>
	<?= $form->field($movie, 'genres') ?>
	<?= $form->field($movie, 'rating') ?>
	<?= $form->field($movie, 'original_title') ?>
	<?= $form->field($movie, 'release_date') ?>
	<?= $form->field($movie, 'runtime') ?>
	<?= $form->field($movie, 'overview')->textarea(['rows' => '20']) ?>

	<div class="form-group">
		<div class="col-lg-offset-1 col-lg-11">
			<?= Html::submitButton('Save', ['class' => 'btn btn-primary']) ?>
		</div>
	</div>

	<?php ActiveForm::end(); ?>
</div>

views/site/movies.php
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\grid\GridView;
use yii\grid\ActionColumn;

$this->title					 = 'Movies';
$this->params['breadcrumbs'][]	 = $this->title;
?>
<div class="site-movies">
    <h1>
		<?= Html::encode($this->title) ?>
		<?= Html::a('Popular', ['site/movies']) ?>
		<?= Html::a('On Screen', ['site/movies', 'type' => 'screen']) ?>
	</h1>

	<?php
	echo GridView::widget([
		'dataProvider'	 => $moviesProvider,
		'columns'		 => [
			'id',
			'title',
			'release_date',
			[
				'class'		 => ActionColumn::className(),
				'template'	 => '{view}',
				'buttons'	 => [
					'view' => function ($url, $model) {
						return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', ['site/movie', 'id' => $model->id], [
								'title' => Yii::t('app', 'View'),
						]);
					}
					],
				],
			],
		]);
		?>
</div>